package xemus

import (
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"sync"
	"testing"

	"github.com/Sumex-io/sumex-tradelib/entity"
)

// Key pair and signatures generated by perp-api's own reference signer (signApiRequest in
// perp-api src/auth/api-key-auth.ts) for the seed 0x01..0x20, so these tests pin the Go signer to
// the server's implementation rather than to itself.
const (
	goldenAPIKey    = "ebVWLo_mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ"
	goldenAPISecret = "AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA"
)

func TestSignPayloadMatchesPerpAPIReference(t *testing.T) {
	cases := []struct {
		ts, method, uri, body, want string
	}{
		{
			ts: "1727000000000", method: "GET",
			uri:  "/v1/orders?size=500&status=INCOMPLETE&symbol=PERP_BTC_USDC",
			want: "WkG0Q5lWVk45SohSTVcSOKV-ANSWHDAodahkdJTUtNi2K1Ng2YvH7kNLWhTZhvHWvuxG13kxN6dfCYamAHJrBw",
		},
		{
			ts: "1727000000001", method: "POST", uri: "/v1/orders",
			body: `{"order_price":65000.5,"order_quantity":0.01,"order_type":"LIMIT","side":"BUY","symbol":"PERP_BTC_USDC"}`,
			want: "GtOkXJLWO0c0S2eM6vtjLZCryJTXPFdB-jPX0vVJvaCBIJfIBacb_LbMaiKw2UcAAXbxV4O0eaK0_MqIdSBmCw",
		},
	}
	for _, c := range cases {
		got, err := signPayload(goldenAPISecret, c.ts, c.method, c.uri, []byte(c.body))
		if err != nil {
			t.Fatal(err)
		}
		if got != c.want {
			t.Errorf("%s %s: signature\n got %s\nwant %s", c.method, c.uri, got, c.want)
		}
	}
}

func TestSignPayloadRejectsMalformedSecret(t *testing.T) {
	for _, secret := range []string{"", "not-base64!", base64.RawURLEncoding.EncodeToString(make([]byte, 31))} {
		if _, err := signPayload(secret, "1", "GET", "/", nil); err == nil {
			t.Errorf("secret %q: expected an error", secret)
		}
	}
}

func TestNextTimestampIsStrictlyIncreasingPerKey(t *testing.T) {
	a1 := nextTimestamp("key-a-"+t.Name(), 5000)
	a2 := nextTimestamp("key-a-"+t.Name(), 5000)
	a3 := nextTimestamp("key-a-"+t.Name(), 4000)
	b1 := nextTimestamp("key-b-"+t.Name(), 5000)
	if a1 != "5000" || a2 != "5001" || a3 != "5002" {
		t.Errorf("same key: got %s %s %s, want 5000 5001 5002", a1, a2, a3)
	}
	if b1 != "5000" {
		t.Errorf("other key must not be pushed ahead: got %s", b1)
	}
}

// ===============FAKE PERP-API=================

type recorded struct {
	method string
	uri    string
	body   string
	header http.Header
}

type fakePerpAPI struct {
	t        *testing.T
	mu       sync.Mutex
	routes   map[string]func() (int, string)
	requests []recorded
	seen     map[string]bool
}

// newFakePerpAPI serves canned responses keyed by "METHOD /path" (query excluded) and, like
// perp-api, refuses any signed request whose signature does not verify or repeats one it has seen.
func newFakePerpAPI(t *testing.T) (*fakePerpAPI, *FuturesClient) {
	f := &fakePerpAPI{t: t, routes: map[string]func() (int, string){}, seen: map[string]bool{}}
	srv := httptest.NewServer(http.HandlerFunc(f.serve))
	t.Cleanup(srv.Close)
	c := NewFuturesClient(goldenAPIKey, goldenAPISecret)
	c.BaseURL = srv.URL
	return f, c
}

func (f *fakePerpAPI) on(route string, status int, body string) {
	f.routes[route] = func() (int, string) { return status, body }
}

func (f *fakePerpAPI) serve(w http.ResponseWriter, r *http.Request) {
	body, _ := io.ReadAll(r.Body)
	f.mu.Lock()
	f.requests = append(f.requests, recorded{method: r.Method, uri: r.RequestURI, body: string(body), header: r.Header.Clone()})
	f.mu.Unlock()

	if sig := r.Header.Get("x-signature"); sig != "" {
		pub, _ := base64.RawURLEncoding.DecodeString(r.Header.Get("x-api-key"))
		raw, _ := base64.RawURLEncoding.DecodeString(sig)
		msg := r.Header.Get("x-timestamp") + "\n" + r.Method + "\n" + r.RequestURI + "\n" + string(body)
		if len(pub) != ed25519.PublicKeySize || !ed25519.Verify(pub, []byte(msg), raw) {
			w.WriteHeader(http.StatusUnauthorized)
			_, _ = w.Write([]byte(`{"message":"Invalid credentials","code":"UNAUTHORIZED"}`))
			return
		}
		f.mu.Lock()
		replay := f.seen[sig]
		f.seen[sig] = true
		f.mu.Unlock()
		if replay {
			w.WriteHeader(http.StatusUnauthorized)
			_, _ = w.Write([]byte(`{"message":"Replayed","code":"REPLAYED_REQUEST"}`))
			return
		}
	}

	route, ok := f.routes[r.Method+" "+r.URL.Path]
	if !ok {
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write([]byte(`{"message":"no route","code":"NOT_FOUND"}`))
		return
	}
	status, resp := route()
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = w.Write([]byte(resp))
}

func (f *fakePerpAPI) only(t *testing.T, method, path string) recorded {
	t.Helper()
	var hits []recorded
	for _, r := range f.requests {
		if r.method == method && strings.SplitN(r.uri, "?", 2)[0] == path {
			hits = append(hits, r)
		}
	}
	if len(hits) != 1 {
		t.Fatalf("%s %s: got %d requests, want 1", method, path, len(hits))
	}
	return hits[0]
}

func decodeBody(t *testing.T, r recorded) map[string]interface{} {
	t.Helper()
	dec := json.NewDecoder(strings.NewReader(r.body))
	dec.UseNumber()
	var m map[string]interface{}
	if err := dec.Decode(&m); err != nil {
		t.Fatalf("body %q: %v", r.body, err)
	}
	return m
}

var ctx = context.Background()

// ===============TRANSPORT=================

func TestTransportSignsAndSendsExactBytes(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders", 200, `{"rows":[]}`)
	f.on("GET /v1/algo-orders", 200, `{"rows":[]}`)

	if _, err := c.NewGetOrderList().Symbol("PERP_BTC_USDC").Do(ctx); err != nil {
		t.Fatal(err)
	}
	r := f.only(t, "GET", "/v1/orders")
	if r.uri != "/v1/orders?size=500&status=INCOMPLETE&symbol=PERP_BTC_USDC" {
		t.Errorf("uri = %s", r.uri)
	}
	if r.header.Get("x-api-key") != goldenAPIKey || r.header.Get("x-timestamp") == "" {
		t.Errorf("missing auth headers: %v", r.header)
	}
	if r.header.Get("Content-Type") != "" {
		t.Errorf("a bodiless request must not claim a JSON body, got %q", r.header.Get("Content-Type"))
	}
}

func TestConcurrentIdenticalRequestsAreNotReplays(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/positions", 200, `{"rows":[],"free_collateral":0,"total_collateral_value":0}`)

	var wg sync.WaitGroup
	errs := make(chan error, 20)
	for i := 0; i < 20; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, err := c.NewGetPositions().Do(ctx)
			errs <- err
		}()
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Fatal(err)
		}
	}
}

func TestErrorsCarryPerpAPICodeAndAreNotRetried(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/positions", 502, `{"message":"Orderly is unavailable","code":"ORDERLY_ERROR"}`)

	_, err := c.NewGetPositions().Do(ctx)
	if err == nil || !strings.Contains(err.Error(), "ORDERLY_ERROR") || !strings.Contains(err.Error(), "Orderly is unavailable") {
		t.Fatalf("err = %v", err)
	}
	if !isAPIErrorCode(err, 502, "ORDERLY_ERROR") {
		t.Errorf("err is not a typed apiError: %#v", err)
	}
	f.only(t, "GET", "/v1/positions")
}

func TestNonJSONErrorBodyIsBounded(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/positions", 502, "<html>"+strings.Repeat("x", 2000)+"</html>")

	_, err := c.NewGetPositions().Do(ctx)
	if err == nil || !strings.Contains(err.Error(), "(truncated)") || len(err.Error()) > 700 {
		t.Fatalf("err = %v", err)
	}
}

func TestUnconfiguredHostFailsClosed(t *testing.T) {
	SetBaseURLs("", "")
	c := NewFuturesClient(goldenAPIKey, goldenAPISecret)
	if _, err := c.NewGetPositions().Do(ctx); err != errHostNotConfigured {
		t.Fatalf("err = %v", err)
	}

	SetBaseURLs("https://perp.example/", "")
	t.Cleanup(func() { SetBaseURLs("", "") })
	c = NewFuturesClient(goldenAPIKey, goldenAPISecret)
	if c.BaseURL != "https://perp.example" {
		t.Errorf("BaseURL = %q", c.BaseURL)
	}
	c.SetDemo(true)
	if _, err := c.NewGetPositions().Do(ctx); err != errHostNotConfigured {
		t.Fatalf("demo without a demo host: err = %v", err)
	}
}

// ===============ACCOUNT=================

func TestAccountInfo(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/info", 200, `{"account_id":"0xabc","max_leverage":10,"taker_fee_rate":5,"maker_fee_rate":2}`)

	got, err := c.NewGetAccountInfo().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	want := entity.AccountInformation{UID: "0xabc", IP: "0.0.0.0/0", CanRead: true, CanTrade: true, PermFutures: true}
	if got.UID != want.UID || !got.CanRead || !got.CanTrade || got.CanTransfer || got.PermSpot || !got.PermFutures {
		t.Errorf("got %+v", got)
	}
}

func TestSignAuthStreamCarriesOrderlyLogin(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/account/stream-signature", 200, `{"accountId":"0xabc","orderlyKey":"ed25519:KEY","timestamp":1727000000000,"signature":"SIG","url":"wss://ws-private-evm.orderly.org/v2/ws/private/stream/0xabc"}`)

	got, err := c.NewSignAuthStream().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got.Signature != "SIG" || got.Timestamp != 1727000000000 || got.AccountID != "0xabc" || got.Key != "ed25519:KEY" || !strings.HasPrefix(got.URL, "wss://") {
		t.Errorf("got %+v", got)
	}
	if r := f.only(t, "POST", "/v1/account/stream-signature"); r.body != "" || r.header.Get("Content-Type") != "" {
		t.Errorf("stream-signature must go out bodiless, got body %q ct %q", r.body, r.header.Get("Content-Type"))
	}
}

// ===============READS=================

func TestInstrumentsInfo(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/markets/symbols", 200, `[
		{"symbol":"PERP_ETH_USDC","quote_tick":0.01,"base_min":0.001,"base_tick":0.001,"min_notional":10,"base_imr":0.05,"status":"REDUCE_ONLY"},
		{"symbol":"PERP_1000PEPE_USDC","quote_tick":1e-7,"base_min":1,"base_tick":1,"min_notional":10,"base_imr":0.1},
		{"symbol":"PERP_BTC_USDC","quote_tick":0.1,"base_min":0.00001,"base_tick":0.00001,"min_notional":10,"base_imr":0.03,"status":"ACTIVE"},
		{"symbol":"SPOT_BTC_USDC","quote_tick":0.1}
	]`)

	got, err := c.NewGetInstrumentsInfo().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Fatalf("got %d instruments, want 3 (non-PERP skipped): %+v", len(got), got)
	}
	pepe, btc, eth := got[0], got[1], got[2]
	if pepe.Symbol != "PERP_1000PEPE_USDC" || pepe.Base != "1000PEPE" || pepe.Quote != "USDC" || pepe.PricePrecision != "7" || pepe.SizePrecision != "0" || pepe.State != "LIVE" || pepe.MaxLeverage != "10" {
		t.Errorf("pepe = %+v", pepe)
	}
	if btc.MinQty != "0.00001" || btc.SizePrecision != "5" || btc.MaxLeverage != "33" || btc.State != "LIVE" || btc.MinNotional != "10" {
		t.Errorf("btc = %+v", btc)
	}
	if eth.State != "REDUCE_ONLY" {
		t.Errorf("a reduce-only market must not be LIVE: %+v", eth)
	}
	if r := f.only(t, "GET", "/v1/markets/symbols"); r.header.Get("x-signature") != "" {
		t.Error("the public catalog must go out unsigned")
	}
}

const positionsFixture = `{
	"free_collateral": 900.5,
	"total_collateral_value": 1015,
	"rows": [
		{"symbol":"PERP_BTC_USDC","position_qty":0.02,"cost_position":1200,"average_open_price":60000,"mark_price":61000,"unsettled_pnl":20,"est_liq_price":null,"leverage":10,"timestamp":1727000000000},
		{"symbol":"PERP_ETH_USDC","position_qty":-1.5,"cost_position":-4500,"average_open_price":3000,"mark_price":2990,"unsettled_pnl":15,"est_liq_price":3500,"leverage":5,"margin_mode":"ISOLATED","margin":300,"timestamp":1727000000001},
		{"symbol":"PERP_SOL_USDC","position_qty":0,"cost_position":0,"average_open_price":0,"mark_price":150,"unsettled_pnl":0,"est_liq_price":null,"leverage":10,"timestamp":1727000000002}
	]
}`

func TestPositions(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/positions", 200, positionsFixture)

	got, err := c.NewGetPositions().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("zero-quantity row must be dropped, got %+v", got)
	}
	btc, eth := got[0], got[1]
	if btc.PositionSide != "LONG" || btc.PositionSize != "0.02" || btc.UnRealizedProfit != "20" || btc.Notional != "1220" || btc.Leverage != "10" || btc.MarginMode != "CROSS" || btc.EntryPrice != "60000" {
		t.Errorf("btc = %+v", btc)
	}
	if eth.PositionSide != "SHORT" || eth.PositionSize != "1.5" || eth.UnRealizedProfit != "15" || eth.Notional != "4485" || eth.MarginMode != "ISOLATED" {
		t.Errorf("eth = %+v", eth)
	}

	only, err := c.NewGetPositions().Symbol("PERP_ETH_USDC").Do(ctx)
	if err != nil || len(only) != 1 || only[0].Symbol != "PERP_ETH_USDC" {
		t.Errorf("symbol filter: %+v %v", only, err)
	}
}

func TestBalance(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/holdings", 200, `{"holding":[
		{"token":"USDC","holding":960,"frozen":10,"pending_short":0,"updated_time":1},
		{"token":"ETH","holding":0.5,"frozen":0,"pending_short":0,"updated_time":1},
		{"token":"SOL","holding":0,"frozen":0,"pending_short":0,"updated_time":1},
		{"token":"WBTC","holding":"1e-3","frozen":0,"pending_short":0,"updated_time":1}
	]}`)
	f.on("GET /v1/positions", 200, positionsFixture)

	got, err := c.NewGetBalance().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	// USDC equity: 960 holding + 20 + 15 unsettled + 300 isolated margin; unrealized 20 + 15.
	want := []entity.FuturesBalance{
		{Asset: "USDC", Balance: "1260", Equity: "1295", Available: "900.5", UnrealizedProfit: "35"},
		{Asset: "ETH", Balance: "0.5", Equity: "0.5", Available: "0.5", UnrealizedProfit: "0"},
		{Asset: "WBTC", Balance: "0.001", Equity: "0.001", Available: "0.001", UnrealizedProfit: "0"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %+v, want %+v", got, want)
	}
}

func TestBalanceKeepsUSDCRowWithoutUSDCHolding(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/holdings", 200, `{"holding":[{"token":"ETH","holding":2,"frozen":0}]}`)
	f.on("GET /v1/positions", 200, `{"free_collateral":5000,"total_collateral_value":6000,"rows":[
		{"symbol":"PERP_BTC_USDC","position_qty":0.1,"cost_position":6000,"average_open_price":60000,"mark_price":59000,"unsettled_pnl":-100,"leverage":10,"timestamp":1}
	]}`)

	got, err := c.NewGetBalance().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	want := []entity.FuturesBalance{
		{Asset: "USDC", Balance: "0", Equity: "-100", Available: "5000", UnrealizedProfit: "-100"},
		{Asset: "ETH", Balance: "2", Equity: "2", Available: "2", UnrealizedProfit: "0"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %+v, want %+v", got, want)
	}
}

func TestOrderListMergesRegularAndTpSlOrders(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders", 200, `{"rows":[
		{"order_id":101,"client_order_id":"xemusABC","symbol":"PERP_BTC_USDC","side":"BUY","type":"POST_ONLY","status":"NEW","price":59000,"quantity":0.01,"executed":0,"average_executed_price":null,"created_time":1,"updated_time":2,"reduce_only":false},
		{"order_id":102,"client_order_id":12345,"symbol":"PERP_BTC_USDC","side":"SELL","type":"LIMIT","status":"PARTIAL_FILLED","price":70000,"quantity":0.02,"executed":0.005,"average_executed_price":70000,"created_time":3,"updated_time":4,"reduce_only":true}
	],"meta":{"total":2}}`)
	f.on("GET /v1/algo-orders", 200, `{"rows":[
		{"algo_order_id":900,"client_order_id":"xemusTPxyz","symbol":"PERP_BTC_USDC","algo_type":"TP_SL","quantity":0.02,"is_triggered":false,"algo_status":"NEW","created_time":5,"updated_time":6,"child_orders":[
			{"algo_order_id":901,"algo_type":"TAKE_PROFIT","side":"SELL","type":"MARKET","trigger_price":72000,"is_triggered":false},
			{"algo_order_id":902,"algo_type":"STOP_LOSS","side":"SELL","type":"LIMIT","trigger_price":55000,"price":54900,"is_triggered":false}
		]},
		{"algo_order_id":950,"symbol":"PERP_BTC_USDC","algo_type":"STOP","side":"BUY","type":"MARKET","quantity":0.01,"trigger_price":75000,"is_triggered":false,"algo_status":"NEW","created_time":7,"updated_time":8,"reduce_only":false},
		{"algo_order_id":960,"symbol":"PERP_BTC_USDC","algo_type":"TRAILING_STOP","side":"SELL","type":"MARKET","quantity":0.01,"is_triggered":false,"algo_status":"NEW"},
		{"algo_order_id":970,"symbol":"PERP_BTC_USDC","algo_type":"STOP","side":"SELL","type":"MARKET","quantity":0.01,"trigger_price":1,"is_triggered":true,"algo_status":"FILLED"}
	]}`)

	got, err := c.NewGetOrderList().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 5 {
		t.Fatalf("got %d rows, want 5: %+v", len(got), got)
	}
	postOnly, closing, tp, sl, stop := got[0], got[1], got[2], got[3], got[4]
	if postOnly.Type != "LIMIT" || postOnly.PositionSide != "LONG" || postOnly.Price != "59000" || postOnly.ClientOrderID != "xemusABC" {
		t.Errorf("post-only = %+v", postOnly)
	}
	if closing.ClientOrderID != "12345" || closing.PositionSide != "LONG" || closing.ExecutedSize != "0.005" || closing.Status != "PARTIAL_FILLED" {
		t.Errorf("reduce-only = %+v", closing)
	}
	if tp.OrderID != "900" || !tp.TpOrder || tp.SlOrder || tp.Type != "TAKE_PROFIT_MARKET" || tp.Price != "72000" || tp.PositionSide != "LONG" || tp.PositionSize != "0.02" {
		t.Errorf("tp = %+v", tp)
	}
	if sl.OrderID != "900" || !sl.SlOrder || sl.Type != "STOP" || sl.Price != "55000" {
		t.Errorf("sl = %+v", sl)
	}
	if stop.OrderID != "algo-950" || stop.Type != "STOP_MARKET" || stop.PositionSide != "LONG" || stop.TpOrder || stop.SlOrder {
		t.Errorf("stop = %+v", stop)
	}
	if r := f.only(t, "GET", "/v1/algo-orders"); r.uri != "/v1/algo-orders?size=500&status=INCOMPLETE" {
		t.Errorf("algo uri = %s", r.uri)
	}
}

func TestOrdersHistory(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders", 200, `{"rows":[
		{"order_id":101,"client_order_id":"xemusABC","symbol":"PERP_BTC_USDC","side":"SELL","type":"MARKET","status":"FILLED","price":null,"quantity":0.01,"executed":0.01,"total_executed_quantity":0.01,"average_executed_price":61000.5,"total_fee":0.3,"fee_asset":"USDC","created_time":1,"updated_time":2,"reduce_only":true,"margin_mode":"ISOLATED"}
	],"meta":{"total":1}}`)

	got, err := c.NewOrdersHistory().Symbol("PERP_BTC_USDC").StartTime(1000).EndTime(2000).Limit(9999).Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %+v", got)
	}
	o := got[0]
	if o.Price != "" || o.ExecutedPrice != "61000.5" || o.Fee != "0.3" || o.FeeAsset != "USDC" || o.PositionSide != "LONG" || o.MarginMode != "ISOLATED" || o.Type != "MARKET" {
		t.Errorf("got %+v", o)
	}
	r := f.only(t, "GET", "/v1/orders")
	if r.uri != "/v1/orders?end_t=2000&size=500&sort_by=CREATED_TIME_DESC&start_t=1000&status=COMPLETED&symbol=PERP_BTC_USDC" {
		t.Errorf("uri = %s", r.uri)
	}
}

func TestPositionsHistory(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/history/positions", 200, `{"rows":[
		{"position_id":7,"position_status":"closed","symbol":"PERP_BTC_USDC","avg_open_price":60000,"avg_close_price":62000,"max_position_qty":0.1,"closed_position_qty":0.1,"side":"LONG","trading_fee":1.2,"accumulated_funding_fee":-0.4,"realized_pnl":198.8,"open_timestamp":1000,"close_timestamp":5000,"last_update_time":5000,"leverage":10,"margin_mode":1},
		{"position_id":8,"position_status":"opened","symbol":"PERP_BTC_USDC","max_position_qty":0.1,"closed_position_qty":0,"side":"SHORT","open_timestamp":6000,"last_update_time":6000},
		{"position_id":9,"position_status":"closed","symbol":"PERP_ETH_USDC","max_position_qty":1,"closed_position_qty":1,"side":"SHORT","open_timestamp":100,"close_timestamp":200,"margin_mode":"CROSS"}
	]}`)

	got, err := c.NewPositionsHistory().StartTime(1000).Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("want only the closed row inside the window, got %+v", got)
	}
	p := got[0]
	if p.PositionID != "7" || p.PositionSide != "LONG" || p.RealisedProfit != "198.8" || p.Funding != "-0.4" || p.MarginMode != "ISOLATED" || p.CreateTime != 1000 || p.UpdateTime != 5000 || p.ExecutedAvgPrice != "62000" {
		t.Errorf("got %+v", p)
	}
	if r := f.only(t, "GET", "/v1/history/positions"); r.uri != "/v1/history/positions?limit=100" {
		t.Errorf("uri = %s", r.uri)
	}
}

func TestPositionsHistoryNullRows(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/history/positions", 200, `{"rows":null}`)
	got, err := c.NewPositionsHistory().Do(ctx)
	if err != nil || got == nil || len(got) != 0 {
		t.Fatalf("got %+v %v", got, err)
	}
}

func TestUserTrades(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/trades", 200, `{"rows":[
		{"id":55,"order_id":101,"symbol":"PERP_BTC_USDC","side":"BUY","executed_price":60000,"executed_quantity":0.02,"fee":0.36,"fee_asset":"USDC","is_maker":1,"executed_timestamp":1727000000000}
	],"meta":{"total":1}}`)

	got, err := c.NewUserTrades().Symbol("PERP_BTC_USDC").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	tr := got[0]
	if tr.TradeID != "55" || tr.OrderID != "101" || tr.QuoteQty != "1200" || !tr.Maker || !tr.Buyer || tr.Commission != "0.36" || tr.Time != 1727000000000 {
		t.Errorf("got %+v", tr)
	}
}

func TestGetLeverage(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/leverages", 200, `{"rows":[{"symbol":"PERP_ETH_USDC","leverage":20,"margin_mode":"ISOLATED"}]}`)
	f.on("GET /v1/account/info", 200, `{"account_id":"0xabc","max_leverage":10,"taker_fee_rate":5,"maker_fee_rate":2}`)

	eth, err := c.NewGetLeverage().Symbol("PERP_ETH_USDC").Do(ctx)
	if err != nil || eth.Leverage != "20" || eth.LongLeverage != "20" || eth.MarginMode != "ISOLATED" {
		t.Errorf("eth = %+v %v", eth, err)
	}
	btc, err := c.NewGetLeverage().Symbol("PERP_BTC_USDC").Do(ctx)
	if err != nil || btc.Leverage != "10" {
		t.Errorf("unset symbol must fall back to the account leverage: %+v %v", btc, err)
	}
}

func TestGetLeverageAcceptsBareArray(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/leverages", 200, `[{"symbol":"PERP_ETH_USDC","leverage":3}]`)
	got, err := c.NewGetLeverage().Symbol("PERP_ETH_USDC").Do(ctx)
	if err != nil || got.Leverage != "3" {
		t.Errorf("got %+v %v", got, err)
	}
}

func TestMarginMode(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/account/margin-modes", 200, `{"rows":[{"symbol":"PERP_ETH_USDC","default_margin_mode":"ISOLATED"}]}`)
	f.on("POST /v1/account/margin-mode", 200, `{}`)

	eth, _ := c.NewGetMarginMode().Symbol("PERP_ETH_USDC").Do(ctx)
	btc, _ := c.NewGetMarginMode().Symbol("PERP_BTC_USDC").Do(ctx)
	if eth.MarginMode != "ISOLATED" || btc.MarginMode != "CROSS" {
		t.Errorf("eth=%+v btc=%+v", eth, btc)
	}

	if _, err := c.NewSetMarginMode().Symbol("PERP_BTC_USDC").MarginMode("isolatd").Do(ctx); err == nil {
		t.Error("a misspelt margin mode must be refused, not defaulted")
	}
	got, err := c.NewSetMarginMode().Symbol("PERP_BTC_USDC").MarginMode("isolated").Do(ctx)
	if err != nil || got.MarginMode != "ISOLATED" {
		t.Fatalf("got %+v %v", got, err)
	}
	if r := f.only(t, "POST", "/v1/account/margin-mode"); r.body != `{"default_margin_mode":"ISOLATED","symbol":"PERP_BTC_USDC"}` {
		t.Errorf("body = %s", r.body)
	}
}

// ===============WRITES=================

func TestSetLeverage(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/account/leverage", 200, `{}`)

	for _, bad := range []string{"2.5", "0", "101", "abc"} {
		if _, err := c.NewSetLeverage().Symbol("PERP_BTC_USDC").Leverage(bad).Do(ctx); err == nil {
			t.Errorf("leverage %q must be refused", bad)
		}
	}
	got, err := c.NewSetLeverage().Symbol("PERP_BTC_USDC").Leverage("20.0").Do(ctx)
	if err != nil || got.Leverage != "20" || got.ShortLeverage != "20" {
		t.Fatalf("got %+v %v", got, err)
	}
	if r := f.only(t, "POST", "/v1/account/leverage"); r.body != `{"leverage":20,"symbol":"PERP_BTC_USDC"}` {
		t.Errorf("body = %s", r.body)
	}
}

func TestPlaceLimitOrderSendsNumbers(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/orders", 201, `{"order_id":123,"client_order_id":"xemusABC","order_type":"LIMIT","order_price":65000.5,"order_quantity":0.01}`)

	got, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("buy").OrderType("limit").Size("0.01").Price("65000.5").ClientOrderID("xemusABC").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "123" || got[0].ClientOrderID != "xemusABC" || got[0].Ts == 0 {
		t.Errorf("got %+v", got)
	}
	r := f.only(t, "POST", "/v1/orders")
	want := `{"client_order_id":"xemusABC","order_price":65000.5,"order_quantity":0.01,"order_type":"LIMIT","side":"BUY","symbol":"PERP_BTC_USDC"}`
	if r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
	if r.header.Get("Content-Type") != "application/json" {
		t.Errorf("content-type = %q", r.header.Get("Content-Type"))
	}
}

func TestPlaceMarketReduceOnlyOmitsPrice(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/orders", 201, `{"order_id":124,"client_order_id":"generated-uuid"}`)

	got, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("MARKET").Size("0.01").Price("61000").Reduce(true).MarginMode("isolated").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].ClientOrderID != "generated-uuid" {
		t.Errorf("the server-generated client id must be reported: %+v", got)
	}
	body := decodeBody(t, f.only(t, "POST", "/v1/orders"))
	if _, ok := body["order_price"]; ok {
		t.Errorf("a MARKET order must not carry a price: %v", body)
	}
	if body["reduce_only"] != true || body["margin_mode"] != "ISOLATED" {
		t.Errorf("body = %v", body)
	}
}

func TestPlaceTakeProfitIsSingleLegTpSl(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/algo-orders", 201, `{"order_id":900,"client_order_id":"xemusTPabc","algo_type":"TP_SL","quantity":0.02}`)

	// The platform's set-TP path: orderType LIMIT, the trigger level in price, no tpPrice.
	got, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("LIMIT").Size("0.02").Price("72000").ClientOrderID("xemusTPabc").TpOrder(true).Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "900" {
		t.Errorf("got %+v", got)
	}
	r := f.only(t, "POST", "/v1/algo-orders")
	want := `{"algo_type":"TP_SL","child_orders":[{"algo_type":"TAKE_PROFIT","side":"SELL","trigger_price":72000,"type":"MARKET"}],"client_order_id":"xemusTPabc","quantity":0.02,"symbol":"PERP_BTC_USDC"}`
	if r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
}

func TestPlaceStopLossPrefersSlPrice(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/algo-orders", 201, `{"order_id":901,"client_order_id":"x"}`)

	if _, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("LIMIT").Size("0.02").Price("1").SlPrice("55000").SlOrder(true).Do(ctx); err != nil {
		t.Fatal(err)
	}
	body := decodeBody(t, f.only(t, "POST", "/v1/algo-orders"))
	leg := body["child_orders"].([]interface{})[0].(map[string]interface{})
	if leg["algo_type"] != "STOP_LOSS" || leg["trigger_price"] != json.Number("55000") || leg["type"] != "MARKET" {
		t.Errorf("leg = %v", leg)
	}
}

func TestPlaceOrderRefusals(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/orders", 201, `{"order_id":1}`)
	f.on("POST /v1/algo-orders", 201, `{"order_id":1}`)

	cases := map[string]*futures_placeOrder{
		"tp on post-only":     c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("POST_ONLY").Size("0.01").Price("60000").TpPrice("70000"),
		"tp on reduce-only":   c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("MARKET").Size("0.01").Reduce(true).SlPrice("70000"),
		"bad tp price":        c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("MARKET").Size("0.01").TpPrice("7e4"),
		"tp and sl":           c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("LIMIT").Size("0.01").Price("1").TpOrder(true).SlOrder(true),
		"tp without trigger":  c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("LIMIT").Size("0.01").TpOrder(true),
		"limit without price": c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("LIMIT").Size("0.01"),
		"stop order type":     c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("STOP").Size("0.01").Price("1"),
		"bad client id":       c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("MARKET").Size("0.01").ClientOrderID("has space"),
		"exponent size":       c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("MARKET").Size("1e-3"),
		"injection in price":  c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("LIMIT").Size("1").Price(`1,"reduce_only":true`),
		"zero size":           c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("MARKET").Size("0"),
		"bad side":            c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("LONG").OrderType("MARKET").Size("1"),
	}
	for name, b := range cases {
		if _, err := b.Do(ctx); err == nil {
			t.Errorf("%s: expected a refusal", name)
		}
	}
	if len(f.requests) != 0 {
		t.Errorf("refusals must not reach perp-api, got %d requests", len(f.requests))
	}
}

func TestCancelOrderRoutes(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("DELETE /v1/orders/123", 200, `{"status":"CANCEL_SENT"}`)
	f.on("DELETE /v1/algo-orders/900", 200, `{"status":"CANCEL_SENT"}`)

	if _, err := c.NewCancelOrder().Symbol("PERP_BTC_USDC").OrderID("123").Do(ctx); err != nil {
		t.Fatal(err)
	}
	got, err := c.NewCancelOrder().Symbol("PERP_BTC_USDC").OrderID("900").TpSl(true).Do(ctx)
	if err != nil || got[0].OrderID != "900" {
		t.Fatalf("got %+v %v", got, err)
	}
	if r := f.only(t, "DELETE", "/v1/orders/123"); r.uri != "/v1/orders/123?symbol=PERP_BTC_USDC" || r.body != "" {
		t.Errorf("regular cancel = %+v", r)
	}
	f.only(t, "DELETE", "/v1/algo-orders/900")

	if _, err := c.NewCancelOrder().Symbol("PERP_BTC_USDC").OrderID("../account").Do(ctx); err == nil {
		t.Error("a non-numeric order id must be refused")
	}
}

func TestAmendOrderKeepsUnchangedFields(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders/123", 200, `{"order_id":123,"client_order_id":"xemusABC","symbol":"PERP_BTC_USDC","side":"BUY","type":"POST_ONLY","status":"NEW","price":59000,"quantity":0.01,"executed":0,"average_executed_price":null,"created_time":1,"updated_time":2,"reduce_only":true}`)
	f.on("PUT /v1/orders/123", 200, `{"status":"EDIT_SENT"}`)

	got, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("123").NewPrice("59500").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "123" || got[0].ClientOrderID != "xemusABC" {
		t.Errorf("got %+v", got)
	}
	r := f.only(t, "PUT", "/v1/orders/123")
	want := `{"order_price":59500,"order_quantity":0.01,"order_type":"POST_ONLY","reduce_only":true,"side":"BUY","symbol":"PERP_BTC_USDC"}`
	if r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
}

func TestAmendOrderRefusals(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders/123", 200, `{"order_id":123,"symbol":"PERP_BTC_USDC","side":"BUY","type":"LIMIT","status":"NEW","price":59000,"quantity":0.01,"executed":0,"average_executed_price":null,"created_time":1,"updated_time":2}`)
	f.on("PUT /v1/orders/123", 200, `{}`)

	if _, err := c.NewAmendOrder().Symbol("PERP_ETH_USDC").OrderID("123").NewPrice("1").Do(ctx); err == nil {
		t.Error("an order on another symbol must be refused")
	}
	if _, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("123").Side("SELL").NewPrice("1").Do(ctx); err == nil {
		t.Error("a side flip must be refused")
	}
	if _, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("123").Do(ctx); err == nil {
		t.Error("an amend with nothing to change must be refused")
	}
	for _, r := range f.requests {
		if r.method == http.MethodPut {
			t.Errorf("a refused amend must not be sent: %+v", r)
		}
	}
}

// ===============BRACKET AND ALGO EDITS=================

func TestPlaceOrderWithTpSlIsBracket(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/algo-orders", 201, `{"order_id":800,"client_order_id":"xemusBR","algo_type":"BRACKET","quantity":0.01}`)

	got, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("BUY").OrderType("LIMIT").Size("0.01").Price("60000").TpPrice("70000").SlPrice("55000").ClientOrderID("xemusBR").MarginMode("cross").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "algo-800" || got[0].ClientOrderID != "xemusBR" {
		t.Errorf("got %+v", got)
	}
	r := f.only(t, "POST", "/v1/algo-orders")
	want := `{"algo_type":"BRACKET","child_orders":[{"algo_type":"POSITIONAL_TP_SL","child_orders":[{"algo_type":"TAKE_PROFIT","side":"SELL","trigger_price":70000,"type":"CLOSE_POSITION"},{"algo_type":"STOP_LOSS","side":"SELL","trigger_price":55000,"type":"CLOSE_POSITION"}]}],"client_order_id":"xemusBR","margin_mode":"CROSS","price":60000,"quantity":0.01,"side":"BUY","symbol":"PERP_BTC_USDC","type":"LIMIT"}`
	if r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
}

func TestPlaceMarketBracketWithStopLossOnly(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("POST /v1/algo-orders", 201, `{"order_id":801}`)

	if _, err := c.NewPlaceOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderType("MARKET").Size("0.01").Price("61000").SlPrice("65000").Do(ctx); err != nil {
		t.Fatal(err)
	}
	body := decodeBody(t, f.only(t, "POST", "/v1/algo-orders"))
	if _, ok := body["price"]; ok {
		t.Errorf("a MARKET bracket must not carry a price: %v", body)
	}
	legs := body["child_orders"].([]interface{})[0].(map[string]interface{})["child_orders"].([]interface{})
	if len(legs) != 1 {
		t.Fatalf("legs = %v", legs)
	}
	leg := legs[0].(map[string]interface{})
	if leg["algo_type"] != "STOP_LOSS" || leg["side"] != "BUY" || leg["trigger_price"] != json.Number("65000") {
		t.Errorf("leg = %v", leg)
	}
}

func TestOrderListBrackets(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/orders", 200, `{"rows":[]}`)
	f.on("GET /v1/algo-orders", 200, `{"rows":[
		{"algo_order_id":800,"root_algo_order_id":800,"client_order_id":"xemusBR","symbol":"PERP_BTC_USDC","algo_type":"BRACKET","side":"BUY","type":"LIMIT","price":60000,"quantity":0.01,"is_triggered":false,"algo_status":"NEW","child_orders":[
			{"algo_order_id":810,"algo_type":"POSITIONAL_TP_SL","is_triggered":false,"child_orders":[
				{"algo_order_id":811,"algo_type":"TAKE_PROFIT","side":"SELL","type":"CLOSE_POSITION","trigger_price":70000,"is_triggered":false,"is_activated":false}
			]}
		]},
		{"algo_order_id":820,"root_algo_order_id":820,"symbol":"PERP_ETH_USDC","algo_type":"BRACKET","side":"SELL","type":"MARKET","quantity":1,"is_triggered":true,"algo_status":"NEW","child_orders":[
			{"algo_order_id":830,"algo_type":"POSITIONAL_TP_SL","is_triggered":false,"child_orders":[
				{"algo_order_id":831,"algo_type":"TAKE_PROFIT","side":"BUY","type":"CLOSE_POSITION","trigger_price":2000,"is_triggered":false,"is_activated":true},
				{"algo_order_id":832,"algo_type":"STOP_LOSS","side":"BUY","type":"CLOSE_POSITION","trigger_price":3000,"is_triggered":false,"is_activated":false}
			]}
		]},
		{"algo_order_id":850,"root_algo_order_id":840,"symbol":"PERP_SOL_USDC","algo_type":"POSITIONAL_TP_SL","is_triggered":false,"algo_status":"NEW","child_orders":[
			{"algo_order_id":851,"algo_type":"STOP_LOSS","side":"SELL","type":"CLOSE_POSITION","trigger_price":100,"is_triggered":false}
		]}
	]}`)

	got, err := c.NewGetOrderList().Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Fatalf("got %d rows, want 3: %+v", len(got), got)
	}
	entry, filledTP, surfacedSL := got[0], got[1], got[2]
	if entry.OrderID != "algo-800" || entry.Type != "LIMIT" || entry.Price != "60000" || entry.PositionSide != "LONG" || entry.PositionSize != "0.01" || entry.TpOrder || entry.SlOrder {
		t.Errorf("pending bracket entry = %+v", entry)
	}
	if filledTP.OrderID != "820" || !filledTP.TpOrder || filledTP.Type != "TAKE_PROFIT_MARKET" || filledTP.Price != "2000" || filledTP.PositionSide != "SHORT" {
		t.Errorf("filled bracket TP = %+v", filledTP)
	}
	if surfacedSL.OrderID != "840" || !surfacedSL.SlOrder {
		t.Errorf("a leg group on its own row must carry its root id: %+v", surfacedSL)
	}
}

func TestCancelAlgoRefRoutesToAlgoOrders(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("DELETE /v1/algo-orders/800", 200, `{"status":"CANCEL_SENT"}`)

	got, err := c.NewCancelOrder().Symbol("PERP_BTC_USDC").OrderID("algo-800").Do(ctx)
	if err != nil || got[0].OrderID != "algo-800" {
		t.Fatalf("got %+v %v", got, err)
	}
	f.only(t, "DELETE", "/v1/algo-orders/800")
	for _, bad := range []string{"algo-", "algo-x", "algo-algo-1"} {
		if _, err := c.NewCancelOrder().Symbol("PERP_BTC_USDC").OrderID(bad).Do(ctx); err == nil {
			t.Errorf("%q must be refused", bad)
		}
	}
}

const twoLegTpSl = `{"algo_order_id":900,"root_algo_order_id":900,"client_order_id":"xemusTP","symbol":"PERP_BTC_USDC","algo_type":"TP_SL","quantity":0.02,"is_triggered":false,"algo_status":"NEW","child_orders":[
	{"algo_order_id":901,"algo_type":"TAKE_PROFIT","side":"SELL","type":"MARKET","trigger_price":72000,"is_triggered":false,"is_activated":true},
	{"algo_order_id":902,"algo_type":"STOP_LOSS","side":"SELL","type":"MARKET","trigger_price":55000,"is_triggered":false,"is_activated":true}
]}`

func TestAmendTpSlLegTriggerPrice(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/algo-orders/900", 200, twoLegTpSl)
	f.on("PUT /v1/algo-orders/900", 200, `{"status":"EDIT_SENT"}`)

	got, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").Side("SELL").OrderID("900").NewPrice("73000").TpOrder(true).Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "900" || got[0].ClientOrderID != "xemusTP" {
		t.Errorf("got %+v", got)
	}
	r := f.only(t, "PUT", "/v1/algo-orders/900")
	if want := `{"child_orders":[{"order_id":901,"trigger_price":73000}]}`; r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
}

func TestAmendTpSlSizeSetsEveryLeg(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/algo-orders/900", 200, twoLegTpSl)
	f.on("PUT /v1/algo-orders/900", 200, `{}`)

	if _, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").NewSize("0.03").NewPrice("54000").SlOrder(true).Do(ctx); err != nil {
		t.Fatal(err)
	}
	r := f.only(t, "PUT", "/v1/algo-orders/900")
	if want := `{"child_orders":[{"order_id":901,"quantity":0.03},{"order_id":902,"quantity":0.03,"trigger_price":54000}]}`; r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
}

func TestAmendBracketLegGoesThroughItsGroup(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/algo-orders/820", 200, `{"algo_order_id":820,"symbol":"PERP_ETH_USDC","algo_type":"BRACKET","side":"SELL","type":"MARKET","quantity":1,"is_triggered":true,"child_orders":[
		{"algo_order_id":830,"algo_type":"POSITIONAL_TP_SL","is_triggered":false,"child_orders":[
			{"algo_order_id":831,"algo_type":"TAKE_PROFIT","side":"BUY","type":"CLOSE_POSITION","trigger_price":2000,"is_triggered":false,"is_activated":true}
		]}
	]}`)
	f.on("PUT /v1/algo-orders/830", 200, `{}`)

	// A single open leg needs no TpOrder/SlOrder to say which.
	if _, err := c.NewAmendOrder().Symbol("PERP_ETH_USDC").OrderID("820").NewPrice("2100").TpSl(true).Do(ctx); err != nil {
		t.Fatal(err)
	}
	r := f.only(t, "PUT", "/v1/algo-orders/830")
	if want := `{"child_orders":[{"order_id":831,"trigger_price":2100}]}`; r.body != want {
		t.Errorf("body\n got %s\nwant %s", r.body, want)
	}
	if _, err := c.NewAmendOrder().Symbol("PERP_ETH_USDC").OrderID("820").NewSize("2").TpSl(true).Do(ctx); err == nil {
		t.Error("a position TP/SL has no size to amend")
	}
}

func TestAmendAlgoRefEntryAndStop(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/algo-orders/800", 200, `{"algo_order_id":800,"client_order_id":"xemusBR","symbol":"PERP_BTC_USDC","algo_type":"BRACKET","side":"BUY","type":"LIMIT","price":60000,"quantity":0.01,"is_triggered":false,"child_orders":[]}`)
	f.on("PUT /v1/algo-orders/800", 200, `{}`)
	f.on("GET /v1/algo-orders/950", 200, `{"algo_order_id":950,"symbol":"PERP_BTC_USDC","algo_type":"STOP","side":"BUY","type":"MARKET","quantity":0.01,"trigger_price":75000,"is_triggered":false}`)
	f.on("PUT /v1/algo-orders/950", 200, `{}`)

	got, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("algo-800").NewPrice("60500").NewSize("0.02").Do(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if got[0].OrderID != "algo-800" || got[0].ClientOrderID != "xemusBR" {
		t.Errorf("got %+v", got)
	}
	if r := f.only(t, "PUT", "/v1/algo-orders/800"); r.body != `{"price":60500,"quantity":0.02}` {
		t.Errorf("bracket body = %s", r.body)
	}
	if _, err := c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("algo-950").NewPrice("76000").Do(ctx); err != nil {
		t.Fatal(err)
	}
	if r := f.only(t, "PUT", "/v1/algo-orders/950"); r.body != `{"trigger_price":76000}` {
		t.Errorf("stop body = %s", r.body)
	}
}

func TestAmendAlgoRefusals(t *testing.T) {
	f, c := newFakePerpAPI(t)
	f.on("GET /v1/algo-orders/900", 200, twoLegTpSl)
	f.on("GET /v1/algo-orders/820", 200, `{"algo_order_id":820,"symbol":"PERP_ETH_USDC","algo_type":"BRACKET","side":"SELL","type":"MARKET","quantity":1,"is_triggered":true,"child_orders":[]}`)
	f.on("GET /v1/algo-orders/960", 200, `{"algo_order_id":960,"symbol":"PERP_BTC_USDC","algo_type":"TRAILING_STOP","side":"SELL","type":"MARKET","quantity":0.01,"is_triggered":false}`)

	cases := map[string]*futures_amendOrder{
		"which leg":        c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").NewPrice("1").TpSl(true),
		"both legs":        c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").NewPrice("1").TpOrder(true).SlOrder(true),
		"leg side flip":    c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").Side("BUY").NewPrice("1").TpOrder(true),
		"leg client id":    c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").NewClientOrderID("x").TpOrder(true),
		"leg other symbol": c.NewAmendOrder().Symbol("PERP_ETH_USDC").OrderID("900").NewPrice("1").TpOrder(true),
		"flag on algo ref": c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("algo-900").NewPrice("1").TpOrder(true),
		"placed entry":     c.NewAmendOrder().Symbol("PERP_ETH_USDC").OrderID("algo-820").NewPrice("1"),
		"trailing stop":    c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("algo-960").NewPrice("1"),
		"exponent trigger": c.NewAmendOrder().Symbol("PERP_BTC_USDC").OrderID("900").NewPrice("7e4").TpOrder(true),
	}
	for name, b := range cases {
		if _, err := b.Do(ctx); err == nil {
			t.Errorf("%s: expected a refusal", name)
		}
	}
	for _, r := range f.requests {
		if r.method == http.MethodPut {
			t.Errorf("a refused amend must not be sent: %+v", r)
		}
	}
}

// ===============DECIMALS=================

func TestDecimalHelpers(t *testing.T) {
	if got := plainDecimal("1e-7"); got != "0.0000001" {
		t.Errorf("plainDecimal = %s", got)
	}
	if got := plainDecimal("65000.5"); got != "65000.5" {
		t.Errorf("plainDecimal = %s", got)
	}
	if got := decimalPlaces("0.010"); got != "2" {
		t.Errorf("decimalPlaces = %s", got)
	}
	if got := maxLeverageFromIMR("0.02"); got != "50" {
		t.Errorf("maxLeverageFromIMR = %s", got)
	}
	if got := unrealizedPnl("-2", "90", "100"); got != "20" {
		t.Errorf("short unrealized = %s", got)
	}
}
